version: '2'

services:
  qiziriqdb_prod:
    container_name: qiziriqdb_prod
    restart: always
    image: postgres:12.2
    environment:
      POSTGRES_DB: db_qiziriq_prod
      POSTGRES_USER: qiziriquser_prod
      POSTGRES_PASSWORD: qiziriqpass_prod
    networks:
      - qiziriq-network
    volumes:
        - qiziriqdata:/var/lib/postgresql/qiziriqdata/

  qiziriqweb_prod:
    container_name: qiziriqweb_prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:9696
    volumes:
      - static_volume_qiziriq:/home/app/web/static
      - media_volume_qiziriq:/home/app/web/media
    networks:
      - qiziriq-network
    depends_on:
      - qiziriqdb_prod
    ports:
      - "9696:9696"
    env_file:
      - ./.env.prod

  qiziriqnginx:
    container_name: qiziriq-nginx
    restart: always
    build: ./nginx
    volumes:
      - static_volume_qiziriq:/home/app/web/static
      - media_volume_qiziriq:/home/app/web/media
    ports:
      - "9797:9797"
    networks:
      - qiziriq-network
    depends_on:
      - qiziriqweb_prod

volumes:
  qiziriqdata:
  static_volume_qiziriq:
  media_volume_qiziriq:

networks:
  qiziriq-network:
    driver: bridge
